accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java, core/src/main/java/org/vertexium/Element.java, core/src/main/java/org/vertexium/ElementBase.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
-  Fix Unit Tests that were failing
- Added a method that will soft delete a property that matches a given property key, property name and visibility
=> Add soft delete method with a given visibility

core/src/main/java/org/vertexium/query/DefaultGraphQuery.java, core/src/main/java/org/vertexium/query/DefaultGraphQueryIterable.java, core/src/main/java/org/vertexium/query/DefaultGraphQueryIterableWithAggregations.java, core/src/main/java/org/vertexium/query/DefaultMultiVertexQuery.java, core/src/main/java/org/vertexium/query/DefaultVertexQuery.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
This should only affect you if you are running without Elasticsearch. This will do an in-memory terms aggregation of your data.
=> add TermsAggregation support to DefaultGraphQuery

CHANGELOG.md, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java, pom.xml, test/src/main/java/org/vertexium/test/GraphTestBase.java
This change submits an inline server-side Groovy script to remove the field from the document. Previously, the entire document was being re-added, which resulted in a merge, and thus did not remove the property from the index. This caused the element to be returned from queries that matched the deleted property value, and also affected total hit counts and aggregated results.
This is based on the Update API documentation: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-update.html
=> Efficiently delete an element property from its Elasticsearch document

CHANGELOG.md, core/src/main/java/org/vertexium/query/QueryBase.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchGraphQueryIterable.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
This fixes missing date and multiple visibility date aggregations by returning `-1` if the field does not exist and then later filtering those `-1` out of the results from ES.
@srfarley
=> Elasticsearch: fix calendar date field aggregations with multiple visibilities

CHANGELOG.md, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
@sfeng88 @srfarley 
Sorting vertices with values "1-1" and "1-2" previously would not sort consistently because Elasticsearch would tokenize on `-`.
To avoid conflicts with existing "analyzed" sort fields I added a `_s` suffix to sorted fields (which I should have done in the first place anyway).
Can you think of some other unit tests I can add to verify the sort order is correct?
=> Elasticsearch: fix: sort by strings with tokens should not effect sort order

core/src/main/java/org/vertexium/util/IterableUtils.java, core/src/test/java/org/vertexium/util/IterableUtilsTest.java
In order to check for an empty Iterable, it's a little messy to have to get an Iterator, check hasNext, then close the iterator. This encapsulates that logic into an isEmpty method
=> Add a helper method to check for an empty Iterable

inmemory/src/main/java/org/vertexium/inmemory/InMemoryVertex.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
In order to make it behave consistently with the Accumulo implementation. When faced with edges that can be seen to Vertices that can't be seen, getVertices will omit them and getVertexIds will return the ids
=> update InMemoryVertex implementations of getVertices and getVertexIds

accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Unfortunately the unit tests I added won't catch this specific case because it only occurs when mixing ES with Accumulo. I kept them in because they are valid test cases.
=> Accumulo: fix accumulo not cleaning up property with old visibility in search index

core/src/main/java/org/vertexium/query/DefaultVertexQuery.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchVertexQuery.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
@sfeng88 
This commit adds Vertex.query support to query vertices only
connected with a given edge label. Previously any hasEdgeLabel
calls were ignored while querying for vertices from a vertex.
=> Added: Vertex.query limited by connected edge labels

CHANGELOG.md, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
To speed up inserts/updates asynchronously submit element updates.
Benchmark times went from 38s to 3.8s
=> Changed: ElasticSearch: asynchronously submit element updates

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
@sfeng88 @dsingley @mwizeman
According to the Accumulo documentation MultiTableBatchWriter class
enables efficient batch writing to multiple tables. When creating a
batch writer for each table, each has its own memory and network resources.
Using this class these resources may be shared among multiple tables.
add vertices in 4.188s
add edges in 7.733s
add vertices in 4.052s
add edges in 6.296s
=> Changed: AccumuloGraph to use MultiTableBatchWriter

CHANGELOG.md, core/src/main/java/org/vertexium/ElementBase.java, core/src/main/java/org/vertexium/util/PropertyCollection.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Previously reading a property required looping over properties multiple
times to get the property of interest. This commit addresses this by
indexing the properties in a Map and getting them directly.
=> Changed: Speed up property reads by using Maps to directly get the property

pom.xml
Add a version number for the maven deploy plugin to remove warnings about malformed pom files. I also added an empty erlative path to the root node to ensure that we don't accidentally pick up a pom from the parent folder.
=> Fix maven warnings

elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
Hoping this helps clear up some version conflict issues.
=> Change: if the Elasticsearch write queue already contains element flush

accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/ElementMutationBuilder.java, core/src/main/java/org/vertexium/EdgeBuilderBase.java, core/src/main/java/org/vertexium/mutation/AlterPropertyVisibility.java, core/src/main/java/org/vertexium/mutation/EdgeMutation.java, core/src/main/java/org/vertexium/mutation/ExistingEdgeMutation.java, core/src/main/java/org/vertexium/mutation/KeyNameVisibilityPropertySoftDeleteMutation.java, core/src/main/java/org/vertexium/mutation/PropertyPropertySoftDeleteMutation.java, core/src/main/java/org/vertexium/mutation/PropertySoftDeleteMutation.java, core/src/main/java/org/vertexium/util/IncreasingTime.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableElement.java, sql/src/main/java/org/vertexium/sql/SqlTableEdge.java, sql/src/main/java/org/vertexium/sql/SqlTableElement.java, sql/src/main/java/org/vertexium/sql/SqlTableVertex.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Before this commit existing mutations would update the timestamp to now
losing the timestamp set in the mutations. This commit also fixes alter
edge label timestamps.
=> Fix: existing element mutations updating timestamps

accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraphConfiguration.java, accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
By storing the history in a separate table we reduce the overhead of
skipping historic items for 99% of queries which only care about the
current values
=> Added: support storing history in a separate table

accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, core/src/main/java/org/vertexium/PropertyDescriptor.java, core/src/main/java/org/vertexium/search/DefaultSearchIndex.java, core/src/main/java/org/vertexium/search/SearchIndex.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java
Added methods to support deleting multiple properties on a single ES request to minimize collisions.
Fixes: https://github.com/v5analytics/visallo-lts/issues/1983
=> Bulk delete properties

sql/src/main/java/org/vertexium/sql/SqlTableEdge.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
SqlTableEdge wasn't overriding the `appendAddPropertyMetadataMutation` method that updated the sqlTableEdge mutations set.
Added unit tests for both vertices and edges
=> Fix metadata mutations on edge properties

CHANGELOG.md, core/src/main/java/org/vertexium/query/TermsAggregation.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
Currently ElasticSearch defaults the number of results from a terms aggregation to 10. Should we up the default number of results or add this option or both?
=> Added: size to TermsAggregation

CHANGELOG.md, core/src/main/java/org/vertexium/query/AggregationResult.java, core/src/main/java/org/vertexium/query/Percentile.java, core/src/main/java/org/vertexium/query/PercentilesAggregation.java, core/src/main/java/org/vertexium/query/PercentilesResult.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchGraphQueryIterable.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
This adds support for ES percentile aggregations. Unlike other aggregations, we are unable to reduce the results of multiple percentile aggregations into a single answer. Because of this, a percentile aggregation must be run on a field for a specific visibility.
=> Added: Elasticsearch: Support for Percentile Aggregations

.travis.yml, CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloFindPathStrategy.java, core/src/main/java/org/vertexium/GraphBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
=> return paths one hop away when finding path with a max of 2 hops

CHANGELOG.md, core/src/main/java/org/vertexium/query/CompositeGraphQuery.java, core/src/main/java/org/vertexium/query/DefaultGraphQueryIdIterable.java, core/src/main/java/org/vertexium/query/DefaultGraphQueryIterable.java, core/src/main/java/org/vertexium/query/Query.java, core/src/main/java/org/vertexium/query/QueryBase.java, core/src/main/java/org/vertexium/query/QueryResultsIterable.java, core/src/main/java/org/vertexium/query/SortContainersComparator.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchGraphQueryIterable.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchGraphQueryIdIterable.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/EmptyElasticSearchGraphQueryIterable.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/utils/PagingIterable.java, elasticsearch2/src/main/java/org/vertexium/elasticsearch2/ElasticsearchGraphQueryIdIterable.java, elasticsearch2/src/main/java/org/vertexium/elasticsearch2/ElasticsearchGraphQueryIterable.java, elasticsearch2/src/main/java/org/vertexium/elasticsearch2/ElasticsearchSearchQueryBase.java, elasticsearch2/src/main/java/org/vertexium/elasticsearch2/EmptyElasticsearchGraphQueryIterable.java, elasticsearch2/src/main/java/org/vertexium/elasticsearch2/utils/PagingIterable.java, test/src/main/java/org/vertexium/test/GraphTestBase.java, test/src/main/java/org/vertexium/test/util/VertexiumAssert.java
Added the methods:
- Query#vertexIds
- Query#edgeIds
- Query#elementIds
- Query#extendedDataRowIds
This will provide better performance when using elasticsearch as the code will not need to additionally query the data store.
=> Query for id values rather than VertexiumObjects

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/ElementMutationBuilder.java, accumulo/src/main/java/org/vertexium/accumulo/LazyMutableProperty.java, accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueHdfsRef.java, accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTable.java, accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTableRef.java, accumulo/src/main/java/org/vertexium/accumulo/keys/DataTableRowKey.java, accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java, core/src/main/java/org/vertexium/property/StreamingPropertyValueRef.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryStreamingPropertyValueRef.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableElement.java, sql/src/main/java/org/vertexium/sql/SqlStreamingPropertyValueRef.java, sql/src/main/java/org/vertexium/sql/SqlTableElement.java
With the timestamp in the SPV row key it prevents the cleanup of history.
Cherry picked from 2.5.x branch
don't merge until verified
=> Changed: Removed timestamp from streaming property value row key.

accumulo/src/main/java/org/vertexium/accumulo/tools/DeleteHistoricalLegacyStreamingPropertyValueData.java
This is a pretty critical script. It will delete the old SPV data that has timestamps in the key if there exists a SPV without the timstamp.
=> Added: tool to delete historical legacy SPV data

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/tools/DeleteHistoricalLegacyStreamingPropertyValueData.java, accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
I lost some data running `DeleteHistoricalLegacyStreamingPropertyValueData` but thankfully it was recoverable. This should fix this issue.
If you have multiple properties on the same vertex with a common key prefix (eg v1.prop1.key and v1.prop1.keyLonger1 and v1.prop1.keyLonger2) the old code would end up deleting all but one.
=> Fixed: DeleteHistoricalLegacyStreamingPropertyValueData with property keys having common prefix

accumulo/src/main/java/org/vertexium/accumulo/AccumuloEdge.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloVertex.java, accumulo/src/main/java/org/vertexium/accumulo/util/DataInputStreamUtils.java
Using decode Text when only a string is needed causes unnecessary garbage `Text` and `char[]` objects.
=> If only a string is needed, use decodeString rather than decodeText

elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java, multimodule-test/accumulo-elasticsearch5/src/test/java/org/vertexium/multimodule/AccumuloElasticsearch5Test.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
The ES5 documentation notes that Painless is safer and several times faster than the alternatives. This PR switches the Vertexium scripts to take advantage of this.
=> Convert ES5 Groovy scripts to use Painless scripts

elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
It looks like this was already fixed in the ElasticSearch 1.7 module but missed in the new ElasticSearch 5 code.
=> DOES_NOT_CONTAIN queries should use AND between property names

elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/utils/InfiniteScrollIterable.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/utils/PagingIterable.java, elasticsearch-singledocument/src/test/java/org/vertexium/elasticsearch/ElasticsearchResource.java, elasticsearch-singledocument/src/test/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndexTest.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/utils/InfiniteScrollIterable.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/utils/PagingIterable.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/ElasticsearchResource.java
Under some situations, when using the limit/skip parameters an extra Elasticsearch query was issued by Vertexium.
=> Fix: Extra Elasticsearch Query with Limit and Skip

CHANGELOG.md, core/src/main/java/org/vertexium/query/CompositeGraphQuery.java, core/src/main/java/org/vertexium/query/DefaultGraphQueryIterable.java, core/src/main/java/org/vertexium/query/DefaultVertexQuery.java, core/src/main/java/org/vertexium/query/Query.java, core/src/main/java/org/vertexium/query/QueryBase.java, core/src/main/java/org/vertexium/query/QueryParameters.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchMultiVertexQuery.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchVertexQuery.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchMultiVertexQuery.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchVertexQuery.java
This PR adds the ability to filter a query by id, which improves the performance of multivertex queries.
When [running a MultiVertexQuery](https://github.com/visallo/vertexium/blob/master/core/src/main/java/org/vertexium/Graph.java#L760-L777), the [ElasticSearch code was using the DefaultMultiVertexQuery](https://github.com/visallo/vertexium/blob/master/elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java#L1387-L1389) which applies all of the search filters after loading all of the elements. This PR will improve performance by filtering the elements in Elasticsearch before loading them from the datastore.
=> Add a hasId method to the Query class

.travis.yml, CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, core/src/main/java/org/vertexium/search/DefaultSearchIndex.java, core/src/main/java/org/vertexium/search/SearchIndex.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java, pom.xml, test/src/main/java/org/vertexium/test/GraphTestBase.java
When the `markVertexHidden`, `markVertexVisible`, `markEdgeHidden`, and `markEdgeVisible` methods of the `Graph` were being called, the search index was not properly being updated to reflect that. 
This change adds/removes a new field named `__hidden` to the search index document to reflect the fact that it has been hidden for a particular visibility.
NOTE: This problem exists for properties as well, but I did not fix it in this PR. I [opened a new issue to track that bug](https://github.com/visallo/vertexium/issues/178).
=> Update the search index properly for hidden elements

CHANGELOG.md, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java, elasticsearch-singledocument/src/test/java/org/vertexium/elasticsearch/ElasticsearchResource.java, elasticsearch-singledocument/src/test/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndexTest.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/ElasticsearchResource.java, multimodule-test/accumulo-elasticsearch/src/test/java/org/vertexium/multimodule/AccumuloElasticsearchSingleDocumentTest.java, multimodule-test/accumulo-elasticsearch5/src/test/java/org/vertexium/multimodule/AccumuloElasticsearch5Test.java, pom.xml, test/src/main/java/org/vertexium/test/GraphTestBase.java
In the Elasticsearch plugins, adding/updating documents to the index is queued as a future but field removal was immediate. This update also queues field removal to avoid timing issues.
In particular, there was a problem in [AccumuloElement#saveExistingElementMutation](https://github.com/visallo/vertexium/blob/14f748037bf3ec0081324f7cff7a483aecc0cfa6/accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java#L128) if there were property changes as well as an element visibility update.  The ES document was [updated on this line](https://github.com/visallo/vertexium/blob/14f748037bf3ec0081324f7cff7a483aecc0cfa6/accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java#L146). The elementType property was removed and then the ES document was updated again [on this …
=> Queue Elasticsearch field removal

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/utils/PagingIterable.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/utils/PagingIterable.java
`PagingIterable`: Fixed an infinite looping problem in the PagingIterable that may have resulted from a malformed ES document.  
`AccumuloElement`: Fixed a timing issue in `AccumuloElement.saveExistingElementMutation` that resulted in an ES document having both the old and new visibility. Since the update `Future`s happen in parallel, it's important to ensure that the removal of the old permission happens after the updating of the properties.
`Elasticsearch5SearchIndex`: Made a small performance improvement in `Elasticsearch5SearchIndex.removeFieldsFromDocument` that will not bother running the script in Elasticsearch if there are no properties to remove.
`ElasticsearchSingleDocumentSearchIndex`: Same improve as described above for `Elasticsearch5SearchIndex`
=>  Fix Timing Issue and Potential Infinite Loop

multimodule-test/accumulo-elasticsearch/pom.xml, multimodule-test/accumulo-elasticsearch5/pom.xml, multimodule-test/pom.xml
We missed the multi-test module poms when releasing vertexium 3.0.1. Might be because the multi-test modules are not enabled by default, they are enabled by a profile.
=> fix version in pom for multi-module test

CHANGELOG.md, elasticsearch5-plugin/src/main/java/org/vertexium/elasticsearch5/plugin/VertexiumQueryStringQueryBuilder.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/VertexiumQueryStringQueryBuilder.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
When executing a query with both a query string and aggregations, the ES5 plugin was failing by throwing a "not implemented" exception in it's doWriteTo method. This method was being called on the server side when ES5 was trying to cache the shard level results. 
I added a new test to demonstrate the error and after fleshing out the methods on the ES5 plugin it is now passing.
=> Fix Queries with Query String and Aggregations

elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
If a multi-property query included any properties that were defined on the graph but never used, the entire query would return no results. This fixes that by simply logging a message and skipping over the unused properties.
No changelog needed for this as it is fixing a feature that has not been released yet.
=> Fix Multi-Property Queries that include Unused Properties

CHANGELOG.md, core/src/main/java/org/vertexium/query/CompositeGraphQuery.java, core/src/main/java/org/vertexium/query/Query.java, core/src/main/java/org/vertexium/query/QueryBase.java, elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
1. Added `Query.has(Datatype.class)`
1. Added `Query.hasNot(Datatype.class)`
1. Added `Query.has(Iterable<String> propertyNames)`
1. Added `Query.hasNot(Iterable<String> propertyNames)`
As I was updating all of the has containers to support multiple property names, I realized the there was no need for a `MultiPropertyHasValueContainer` so I combined that with the regular `HasValueContainer`.
=> Additional Multi-Property Query Methods

CHANGELOG.md, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
If many items in the flush queue get backed up and hit the retry limit at the same
time the queue can get overflowed with items and continue to cause exceptions
on subseqent calls to flush.
=> Fixed: Elasticsearch flush overflow causing excessive exceptions

CHANGELOG.md, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Let's try this again. Please let travis finish running before merging. Running into weird issues where test pass locally but not in Travis.
NOTE: With this new fix, I made ids sorted ascending order instead of descending order in ES
=> fix pagination returning duplicate ids on different pages

CHANGELOG.md, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
Before this change ES5 could get into a state where large batches would fail again and again because the retry logic would try a batch, sleep, then try the whole batch again, which would typically fail. This change makes it so that a batch is tried, if any of those requests in the batch fails the time between requests will be increased until the requests no longer fail.
=> Fixed: Elasticsearch5 retry logic to sleep per request failure instead of batch of failures

CHANGELOG.md, core/src/main/java/org/vertexium/query/Compare.java, core/src/main/java/org/vertexium/query/DefaultGraphQueryIterableWithAggregations.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchGraphQueryIterable.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
ES keyword fields fail to be found if the case did not match perfectly. This changes allows for case insensitive searching of exact match fields
=> Fixed: Mixed case searching on exact match properties

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTableDataRef.java, accumulo/src/main/java/org/vertexium/accumulo/util/DataInDataTableStreamingPropertyValueStorageStrategy.java, core/src/main/java/org/vertexium/property/StreamingPropertyValue.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Users of `getLength` should still check null lengths though.
=> Fixed: Accumulo stream property value in table data length of reference

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloFindPathStrategy.java, accumulo/src/test/java/org/vertexium/accumulo/AccumuloSimpleSubstitutionGraphTest.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
I also change the unit tests to be for consistent with the labels so that the `AccumuloSimpleSubstitutionGraphTest` can find future errors.
=> Fixed: Find path when edge labels are deflated

CHANGELOG.md, core/src/main/java/org/vertexium/IdFetchHint.java, core/src/main/java/org/vertexium/query/EmptyResultsGraphQuery.java, core/src/main/java/org/vertexium/query/Query.java, core/src/main/java/org/vertexium/query/QueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchExtendedDataQuery.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchVertexQuery.java, test/src/main/java/org/vertexium/test/GraphTestBase.java, test/src/main/java/org/vertexium/test/util/VertexiumAssert.java
Previously, the search index classes were always filtering out results that are hidden. Now, if the FetchHints contain INCLUDE_HIDDEN that filtering will be skipped.
In order to allow this behavior for loadign id's, I also added overloaded versions of `vertexIds`, `edgeIds`, `elementIds`, and `extendedDataRowIds` that take EnumSet<IdFetchHint> indicating whether or not to include hidden.
=> Update Query to Respect FetchHint.INCLUDE_HIDDEN

CHANGELOG.md, core/src/main/java/org/vertexium/query/QueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
If an element's only use of an authorization was for the `__hidden` field, it was not matching as a result for the `Query.hasAuthorization` method.
=> Query.hasAuthorization Missing Hidden Elements

core/src/main/java/org/vertexium/id/UUIDIdGenerator.java
Java's `String.replaceAll` compiles and executes a new regular expression with every call. Since all we need is to remove a single character, the `StringUtils.remove` method in apache commons is more efficient.
=> Don't compile a regular expression for every id generation

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, core/src/main/java/org/vertexium/IdFetchHint.java, core/src/main/java/org/vertexium/query/QueryBase.java, core/src/main/java/org/vertexium/search/DefaultSearchIndex.java, core/src/main/java/org/vertexium/search/SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
If the only use of an authorization was a hidden property, `Query.hasAuthorization` was not returning an element since the search index was not being updated for hidden properties. This PR makes such elements return for `Query.hasAuthorization`, but [does not fix the issue of the hidden properties still being searchable](https://github.com/visallo/vertexium/issues/178). Once that issue is fixed, the `HIDDEN_PROPERTY_FIELD_NAME` can likely be removed.
Known Issue: If a property is marked hidden, it can still be found with a search but it will not be retrieved from the data store.
=> Query.hasAuthorization match elements with hidden properties

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
Rather than creating a new writer for every thread, use a single MultiTableBatchWriter. This allows client programs to more effectively use multi-threading.
=> All Threads Share a Batch Writer

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, core/src/main/java/org/vertexium/mutation/ExistingElementMutation.java, core/src/main/java/org/vertexium/mutation/ExistingElementMutationImpl.java, core/src/main/java/org/vertexium/search/DefaultSearchIndex.java, core/src/main/java/org/vertexium/search/SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
When saving an ExistingElementMutation, the AccumuloElement/AccumuloGraph code would previously make multiple index update requests and up to two refreshes of the search index. This change adds a new method to the SearchIndex to apply an ExistingElementMutation directly. This allows the ES index to be updated with a single request using a painless script. 
As an additional benefit, we were previously sending the entire document as an upsert request which potentially sent more data than necessary. Now we only send the property value for fields that are added by the mutation.
=> Apply ExistingElementMutations with Painless Script in Elasticsearch

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTableData.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
The `InputStream` for a `StreamingPropertyValue` was not being properly reset if `mark` was called before reading any data from the stream.
=> Fix calling InputStream.reset if mark is called before reading data

CHANGELOG.md, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
If calling index.updateElement the conversion wasn't called so would fail if saving a BigDecimal or BigInteger
All tests use InMemoryElement which always calls `addElement`
=> Move property conversion so it's called on updates

accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloVertex.java, core/src/main/java/org/vertexium/search/DefaultSearchIndex.java, core/src/main/java/org/vertexium/search/SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java
When a cluster member is notified of property definition changes, we need to reload the Elasticsearch IndexInfo cache to see the new property definitions.
=> Reload Elasticsearch IndexInfo Cache when Property Definitions Change (3.2)

CHANGELOG.md, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/utils/DefaultBulkProcessorListener.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
The default for the builder is to queue up to 1000 actions and 5MB and to have 1 in-flight request at a time so I think that should work as good defaults.
=> Changed: Elasticsearch to use BulkProcessor

elasticsearch5/pom.xml
On a brand new clone of the Vertexium repo, IntelliJ is not able to find the log4j dependency needed by  `org.vertexium.elasticsearch5.utils.ConsoleAppender`. Prior to this PR, the log4j dependency is transitively included and the Vertexium project's root pom sets the scope as runtime. For some reason, Maven and IntelliJ process this transitive runtime dependency differently. Nevertheless, since `org.vertexium.elasticsearch5.utils.ConsoleAppender` directly extends a log4j class, the log4j dependency should be called out explicitly in its module pom file. This makes IntelliJ happy too.
=> Add explicit test dependency for log4j

elasticsearch5-plugin/src/main/java/org/vertexium/elasticsearch5/plugin/VertexiumQueryStringQueryBuilder.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/VertexiumQueryStringQueryBuilder.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java
This PR turns off default support for wildcards at the start of a query, which alleviates significant performance impacts on large indices.
=> Disallow leading wildcards

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraphConfiguration.java, accumulo/src/main/java/org/vertexium/accumulo/mapreduce/AccumuloElementInputFormatBase.java, accumulo/src/main/java/org/vertexium/accumulo/mapreduce/AccumuloElementOutputFormat.java, elasticsearch5-plugin/src/main/assemblies/plugin-descriptor.properties, elasticsearch5-plugin/src/main/java/org/vertexium/elasticsearch5/plugin/VertexiumQueryStringQueryBuilder.java, pom.xml
Wanted Accumulo 1.9 to get faster performance https://accumulo.apache.org/release/accumulo-1.9.0/#performance-improvements
According to `GraphTestBase#benchmark` running Accumulo
Before...
```
2018-08-01 11:39:21.913/EDT INFO  [vertexium.test.GraphTestBase] add vertices in 0.934s
2018-08-01 11:39:22.784/EDT INFO  [vertexium.test.GraphTestBase] add edges in 0.871s
2018-08-01 11:39:43.282/EDT INFO  [vertexium.test.GraphTestBase] find vertices by id in 20.498s
```
After...
```
2018-08-01 10:25:33.749/EDT INFO  [vertexium.test.GraphTestBase] add vertices in 1.074s
2018-08-01 10:25:34.841/EDT INFO  [vertexium.test.GraphTestBase] add edges in 1.092s
2018-08-01 10:25:50.887/EDT INFO  [vertexium.test.GraphTestBase] find vertices by id in 16.045s
```
So it looks like writes were slightly slower …
=>  Upgrade Elasticsearch version to 5.6.10 and Accumulo to 1.9.2

pom.xml
The previous 0.21.1 was GPL licensed.
=> Upgrade cache2k to newer release with Apache license

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraphLogger.java, accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTable.java, accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTableData.java, accumulo/src/main/java/org/vertexium/accumulo/util/OverflowIntoHdfsStreamingPropertyValueStorageStrategy.java
Fixed: AccumuloGraphLogger was throwing an error when trying to log a field from a Scanner that was removed in [Accumulo 1.8.0](https://github.com/apache/accumulo/commit/a14bc292d2271a4d369d2b3f04cd49e6efc36280#diff-01878db554932cd0ddae68c59402ce76L45)
=> Pass Table Name to AccumuloGraphLogger for a Scanner

CHANGELOG.md, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
If an element has many properties recreating a new list for every new property is expensive.
This will try and add to the existing list unless it is readonly.
=> Elasticsearch: optimize adding properties to vertices/edges with lots of properties

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/keys/KeyHelper.java, core/src/main/java/org/vertexium/GraphBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchIndexConfiguration.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/IndexRefreshTracker.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/ElasticsearchResource.java, elasticsearch5/src/test/java/org/vertexium/elasticsearch5/IndexRefreshTrackerTest.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
This allows multiple writes to happen before a refresh is needed.
=> Elasticsearch: index on reads instead of indexing on writes.

CHANGELOG.md, accumulo-iterators/pom.xml, accumulo-migrations/pom.xml, accumulo/pom.xml, cli/pom.xml, core/pom.xml, cypher/pom.xml, elasticsearch5-plugin/pom.xml, elasticsearch5/pom.xml, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/MetadataTablePropertyNameVisibilitiesStore.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/PropertyNameVisibilitiesStore.java, elasticsearch5/src/main/resources/org/vertexium/elasticsearch5/add-fields-to-extended-data.painless, elasticsearch5/src/main/resources/org/vertexium/elasticsearch5/helper-functions.painless, elasticsearch5/src/main/resources/org/vertexium/elasticsearch5/remove-fields-from-document.painless, elasticsearch5/src/main/resources/org/vertexium/elasticsearch5/update-fields-on-document.painless, inmemory/pom.xml, inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java, kryo-serializer/pom.xml, multimodule-test/accumulo-elasticsearch5/pom.xml, multimodule-test/pom.xml, pom.xml, security/pom.xml, test/pom.xml, test/src/main/java/org/vertexium/test/GraphTestBase.java, xstream-serializer/pom.xml
Updated to make sure that you have access to at least one column for a query to match extended data. Previously, if you had access to the element but none of the extended data columns you could still match on the row using a query with no filters. This resulted in the row being counted in `totalHits` but not loaded by Accumulo, which caused errors in the paging iterables.
=> Fix Extended Data Query with no Access to Columns

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/src/main/resources/org/vertexium/elasticsearch5/add-fields-to-extended-data.painless, elasticsearch5/src/main/resources/org/vertexium/elasticsearch5/update-fields-on-document.painless, inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
When the visibility changes on an element, also update the visibility of the `__elementType` field on all associated extended data.
=> Fix __elementType Visibility on Extended Data

CHANGELOG.md, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/EdgeIterator.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/ElementIterator.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/KeyValue.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/VertexIterator.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/ElementData.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/HiddenProperty.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/IteratorFetchHints.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/IteratorMetadataEntry.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/KeyBaseByteSequence.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/Property.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/PropertyColumnQualifier.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/PropertyColumnQualifierByteSequence.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/PropertyHiddenColumnQualifierByteSequence.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/PropertyMetadataColumnQualifier.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/PropertyMetadataColumnQualifierByteSequence.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/SoftDeletedProperty.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/util/ByteSequenceUtils.java, accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/util/DataOutputStreamUtils.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloNameSubstitutionStrategy.java, accumulo/src/main/java/org/vertexium/accumulo/mapreduce/AccumuloElementInputFormatBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Unit tests pass and based on testing helps by speeding up the iterator by 75% in highly constrained memory environments.
=> Changed: Improve Accumulo iterator memory by not converting values to strings and then back again

CHANGELOG.md, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/util/ConnectorUtils.java, accumulo/src/main/java/org/vertexium/accumulo/util/VisalloTabletServerBatchReader.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Benchmark https://github.com/visallo/vertexium/compare/fast-batch-reader?expand=1#diff-7de8e1270d184f1d847439d3722b3a36R9015
Before change: 36.852s
After change: 24.665s
This change also alleviates the strict need to close the iterator.
=> Accumulo use a thread pool when doing batch scans

accumulo/src/main/java/org/vertexium/accumulo/AccumuloEdge.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, accumulo/src/main/java/org/vertexium/accumulo/AccumuloVertex.java, core/src/main/java/org/vertexium/DefaultElementId.java, core/src/main/java/org/vertexium/DefaultElementLocation.java, core/src/main/java/org/vertexium/Edge.java, core/src/main/java/org/vertexium/EdgeInfoEdge.java, core/src/main/java/org/vertexium/Element.java, core/src/main/java/org/vertexium/ElementId.java, core/src/main/java/org/vertexium/ElementLocation.java, core/src/main/java/org/vertexium/Graph.java, core/src/main/java/org/vertexium/Vertex.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchEdge.java, elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchVertex.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryEdge.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryVertex.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
This allows methods to take an `ElementId` as a parameter and you could just pass the `Element` itself.
FYI makes some of my merge code easier
=> Refactor ElementId to allow Elements to comply with the interface

.travis.yml, accumulo-iterators/pom.xml, accumulo-migrations/pom.xml, accumulo/pom.xml, cli/pom.xml, core/pom.xml, cypher/pom.xml, elasticsearch5-plugin/pom.xml, elasticsearch5/pom.xml, inmemory/pom.xml, kryo-serializer/pom.xml, multimodule-test/accumulo-elasticsearch5/pom.xml, multimodule-test/pom.xml, pom.xml, security/pom.xml, test/pom.xml, xstream-serializer/pom.xml
Can't release 4.6.1 due to this maven error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project vertexium-root: You don't have a SNAPSHOT project in the reactor projects list. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
Bumped the pom version to `4.6.1-SNAPSHOT` and created PR to wait for travis to pass.
=> bump version to 4.6.1-SNAPSHOT

elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/LoadAndAddDocumentMissingHelper.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkItem.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkItemFailure.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkItemList.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkUpdateQueue.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/FailureList.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/PendingFuturesList.java, elasticsearch5/search-index/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java, elasticsearch5/search-index/src/test/java/org/vertexium/elasticsearch5/TestElasticsearch5ExceptionHandler.java
Before this, one thread could cause another thread to wait indefinitly as
long as new writes are coming in.
=> Only wait for items added before flush was called to be flushed

elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkUpdateQueue.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkUpdateService.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/PendingFuturesList.java
I ran into a problem using the new bulk update where it was either dead locking or running into timing issues. Hopefully this simplifies things and solves the issue.
=> rewrite how the BulkUpdateQueue waits for futures to prevent dead locks, excess waiting, etc

core/src/main/java/org/vertexium/util/VertexiumReadWriteLock.java, core/src/main/java/org/vertexium/util/VertexiumStampedLock.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkItemList.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkUpdateQueue.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/bulk/BulkUpdateService.java
- Switch to using StampedLock for performance (https://blog.overops.com/java-8-stampedlocks-vs-readwritelocks-and-synchronized/ has some benchmarks)
- Expose queue submittedItems as a metric
- When waiting for an item to complete be sure to process the failed items because it could be one of those items
These are some tweaks I made on my project that gave better performance and fixed a couple conditions
=> Changes to ES bulk update queue

CHANGELOG.md, core/src/main/java/org/vertexium/query/DefaultGraphQueryIterableWithAggregations.java, core/src/main/java/org/vertexium/query/TermsResult.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/ElasticsearchGraphQueryIterable.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Adds 2 attributes to the TermResult object
1. `docCountErrorUpperBound`
1. `sumOfOtherDocCounts`
=> Add term aggregation result attributes

CHANGELOG.md, core/src/main/java/org/vertexium/query/DefaultGraphQueryIterableWithAggregations.java, core/src/main/java/org/vertexium/query/TermsAggregation.java, core/src/main/java/org/vertexium/query/TermsResult.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/ElasticsearchGraphQueryIterable.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
When performing a `TermsAggregation`, in addition to knowing the terms it's sometimes useful to know how many documents do not have the field at all. This PR adds a new parameter `includeHasNotCount` to the `TermsAggregation` in order to compute this value. It's false by default so that existing code will not incur additional overhead to compute a value they won't be reading.
=> Add a Count of Elements Missing a Field for TermsAggregation

core/src/main/java/org/vertexium/GraphBaseWithSearchIndex.java, core/src/main/java/org/vertexium/metric/DropWizardMetricRegistry.java, core/src/main/java/org/vertexium/metric/NullMetricRegistry.java, core/src/main/java/org/vertexium/metric/VertexiumMetricRegistry.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/MetadataTablePropertyNameVisibilitiesStore.java
We had a case where the graph was shut down and a new graph was created with the same drop wizard metrics registry. As a result, errors were thrown when Vertexium tried to re-register the bulk index gauges. This PR will clean up all metrics registered through the Vertexium registry when the graph is shutdown.
In addition, we noticed a concurrency issue in the `MetadataTablePropertyNameVisibilitiesStore` that is fixed as part of this PR.
=> Clean Up Metrics on Graph Shutdown

elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/DefaultIndexSelectionStrategy.java, elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/DefaultIndexSelectionStrategy.java
When loading index information from ElasticSearch, we encountered a deadlock between two threads. One thread held the lock [here in the index selection strategy](https://github.com/visallo/vertexium/blob/master/elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/DefaultIndexSelectionStrategy.java#L78
). The other thread held the lock [here in the search index](https://github.com/visallo/vertexium/blob/master/elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/Elasticsearch7SearchIndex.java#L275). The result is that these two threads deadlocked and held up all threads in the search index.
This change will cause the `DefaultIndexSelectionStrategy.loadIndicesToQuery` method to potentially get called by multiple threads when the cache expires, but this is …
=> Fix a Deadlock when Loading Indices

CHANGELOG.md, elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/lucene/DefaultQueryStringTransformer.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Elasticsearch 7 query string transformation was improperly stripping escape characters from fields that could not be found in the search index. Now, if the fieldname is not found it will be put back into the query string exactly as it appeared before processing.
=> Fix ElasticSearch 7 Query String Transformation Escaping.

CHANGELOG.md, core/src/main/java/org/vertexium/search/DefaultSearchIndex.java, core/src/main/java/org/vertexium/search/SearchIndex.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java, elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/Elasticsearch7SearchIndex.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
When re-indexing an element with hidden properties in Elasticsearch, the hidden property field was not being included in the list of fields to add.
=>  Fix Re-Indexing Elements with Hidden Properties

CHANGELOG.md, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/ElasticsearchGraphQueryIterable.java, elasticsearch5/search-index/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java, elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/ElasticsearchGraphQueryIterable.java, elasticsearch7/search-index/src/test/java/org/vertexium/elasticsearch7/Elasticsearch7SearchIndexTest.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
In the case of a TermAggregation with no matching fields, it would raise an exception if the caller requested `setIncludeHasNotCount(true)` but work otherwise. This PR fixes that to return the proper number of hits (all of them) in the hasNotCount.
=> Fixed: Term Aggregation with no Matching Fields

CHANGELOG.md, accumulo/graph/src/main/java/org/vertexium/accumulo/StringStreamingPropertyValueRef.java, accumulo/graph/src/main/java/org/vertexium/accumulo/util/DataInDataTableStreamingPropertyValueStorageStrategy.java, core/src/main/java/org/vertexium/property/StreamingPropertyValue.java, core/src/main/java/org/vertexium/property/StringStreamingPropertyValue.java
Add a specialized version on StreamingPropertyValue to be more performant in the case where the value is a String already in memory
=> Add StringStreamingPropertyValue for Faster Indexing

CHANGELOG.md, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/utils/InfiniteScrollIterable.java, elasticsearch5/search-index/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java, elasticsearch5/search-index/src/test/java/org/vertexium/elasticsearch5/ElasticsearchResource.java, elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/ElasticsearchSearchQueryBase.java, elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/utils/InfiniteScrollIterable.java, elasticsearch7/search-index/src/test/java/org/vertexium/elasticsearch7/Elasticsearch7SearchIndexTest.java, elasticsearch7/search-index/src/test/java/org/vertexium/elasticsearch7/ElasticsearchResource.java, pom.xml, test/src/main/java/org/vertexium/test/GraphTestBase.java
Improve detection and logging of Elasticsearch scrolls that are not closed by Vertexium clients. Fixed a few leaks present in the test code and also added a check after every test to fail if a leak is introduced.
=> Improve Detection of Elasticsearch Scroll Leaks

CHANGELOG.md, accumulo/graph/src/main/java/org/vertexium/accumulo/LazyPropertyMetadata.java
Encountered when multiple threads were getting metadata values from the lazy properties of the same vertex.
```
java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1526)
at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1524)
at org.vertexium.accumulo.LazyPropertyMetadata.getEntry(LazyPropertyMetadata.java:180)
```
=> Fix LazyPropertyMetadata ConcurrentModificationException

elasticsearch7/search-index/src/main/resources/org/vertexium/elasticsearch7/update-fields-on-document.painless, elasticsearch7/search-index/src/test/java/org/vertexium/elasticsearch7/Elasticsearch7SearchIndexTest.java
This PR fixes an issue with updating a fvisibility on a field and then updating it again. The result was that the updated field would get its visiblity set correctly, but the value would be set to `null` even though the value is not null. This fix ensures that does not happen.
=> Fix renaming of elementing during search update

CHANGELOG.md, accumulo/graph/src/main/java/org/vertexium/accumulo/LazyMutableProperty.java
Fix a threading issue when creating a cached version of a lazy property value. If two threads attempt to deserialize the value at the same time, there can be timing issues with the way the code sets the non-serialized value to null.
=> Improve LazyMutableProperty Threadsafety

CHANGELOG.md, accumulo/graph/src/main/java/org/vertexium/accumulo/AccumuloGraph.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Note: I didn't test SPV extended data values since it doesn't look like we support them on initial add
=> Fixed: Elasticsearch: Streaming Property Values being indexed as "" after an update of the property

CHANGELOG.md, elasticsearch5/search-index/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java, elasticsearch7/search-index/src/main/java/org/vertexium/elasticsearch7/ElasticsearchSearchQueryBase.java, elasticsearch7/search-index/src/test/java/org/vertexium/elasticsearch7/Elasticsearch7SearchIndexTest.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
Fixed: Sorting issue when ElasticSearch attempts to implicitly cast Date Times to Doubles in search query string
=> Fix implicit casting by ElasticSearch during sorting script

CHANGELOG.md, accumulo/graph/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
Prevents memory leak because the event queue was never getting cleared
=> Fixed: Accumulo: don't queue events when no event listeners are attached

CHANGELOG.md, core/src/main/java/org/vertexium/HasPropertiesIgnoringFetchHints.java, core/src/main/java/org/vertexium/query/QueryBase.java, inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java, inmemory/src/test/java/org/vertexium/inmemory/InMemoryGraphTest.java, multimodule-test/accumulo-elasticsearch5/src/test/java/org/vertexium/multimodule/AccumuloElasticsearch5Test.java, multimodule-test/accumulo-elasticsearch7/src/test/java/org/vertexium/multimodule/AccumuloElasticsearch7Test.java, test/src/main/java/org/vertexium/test/GraphTestBase.java
To have better feature parity with Accumulo/ES graph add support to InMemoryGraph
to run property graph queries with FetchHints.NONE.
```
graph.query()
.has("firstName", "Joe")
.vertices(FetchHints.NONE)
```
=> Changed: InMemory: Support property graph queries with FetchHints.NONE
