visallo/vertexium

- accumulo/src/main/java/org/neolumin/vertexium/accumulo/AccumuloGraph.java
- accumulo/src/main/java/org/neolumin/vertexium/accumulo/AccumuloGraphConfiguration.java
- accumulo/src/test/java/org/neolumin/vertexium/accumulo/AccumuloGraphConfigurationTest.java
> Allow configuration of accumulo batchwriters

- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTable.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableElement.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Fix soft delete bug for in memory implementation and added test
> Fix in memory implementation

- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
@joeferner just a small improvement to improve the chances of a successful update
> randomizing the single document index update retry time

- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraphConfiguration.java
When graph.hdfs.confDir is passed in, all properties inside of the directory will be returned as part of the hadoop configuration.
> Add optional hdfs.confDir config

- CHANGELOG.md
- sql/src/main/java/org/vertexium/sql/SqlGraphDDL.java
> change the size of SQL varchar

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- accumulo/src/main/java/org/vertexium/accumulo/ElementMutationBuilder.java
- accumulo/src/main/java/org/vertexium/accumulo/mapreduce/ElementMapper.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
See the test for details on what this fixes
> fix saving mutation with the same key/name/visibility properties with different timestamps

- CHANGELOG.md
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/IndexInfo.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
> Elasticsearch: only sort on properties know to be in the index

- CHANGELOG.md
- sql/scripts/create-mysql.sql
- sql/src/main/java/org/vertexium/sql/SqlGraphDDL.java
> SQL: Add indexes to vertex id columns in edge table

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- core/src/main/java/org/vertexium/GraphBaseWithSearchIndex.java
- core/src/main/java/org/vertexium/search/DefaultSearchIndex.java
- core/src/main/java/org/vertexium/search/SearchIndex.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/MetadataTablePropertyNameVisibilitiesStore.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/PropertyNameVisibilitiesStore.java
- elasticsearch-singledocument/src/test/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndexTestBase.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java
> Elasticsearch: load properties mappings from index on startup

- CHANGELOG.md
- core/src/main/java/org/vertexium/query/CalendarFieldAggregation.java
- core/src/main/java/org/vertexium/query/DefaultGraphQueryIterableWithAggregations.java
- core/src/main/java/org/vertexium/query/HistogramResult.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
> add CalendarFieldAggregation

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- core/src/main/java/org/vertexium/search/DefaultSearchIndex.java
- core/src/main/java/org/vertexium/search/SearchIndex.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryEdge.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryVertex.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
> Elasticsearch: fix: Aggregation after alter visibility

- CHANGELOG.md
- pom.xml
- sql/pom.xml
- sql/src/main/java/org/vertexium/sql/SqlGraphConfiguration.java
- sql/src/test/java/org/vertexium/sql/SqlGraphTest.java
Let's try this instead. DBCP didn't really provide the JMX and configuration that I would have liked.
> SQL: Switch to HikariCP connection pool

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraphLogger.java
- accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
- core/src/main/java/org/vertexium/Graph.java
- core/src/main/java/org/vertexium/GraphBase.java
- core/src/main/java/org/vertexium/Range.java
- core/src/test/java/org/vertexium/RangeTest.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Accumulo: add methods to get the tablet splits
@srfarley
> Graph: add methods to get vertices and edges in a range of IDs

- CHANGELOG.md
- core/src/main/java/org/vertexium/GraphBase.java
- core/src/main/java/org/vertexium/query/DefaultGraphQuery.java
@srfarley 
I can't decide if I like this or just removing the warnings all together. Thoughts?
merge PR https://github.com/v5analytics/vertexium/pull/95 first
> Remove excess logging

- CHANGELOG.md
- core/src/main/java/org/vertexium/query/HistogramAggregation.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
> Elasticsearch: Add extended bounds to histograph aggregation

- CHANGELOG.md
- kryo-serializer/README.md
- kryo-serializer/src/main/java/org/vertexium/serializer/kryo/QuickKryoVertexiumSerializer.java
- kryo-serializer/src/test/java/org/vertexium/serializer/kryo/KryoVertexiumSerializerTest.java
By default compression is disabled so this should not affect current installations.
> Quick Kryo Serializer: add support to compress the bytes after serialization

- CHANGELOG.md
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableElement.java
- inmemory/src/main/java/org/vertexium/inmemory/mutations/AddPropertyMetadataMutation.java
- inmemory/src/main/java/org/vertexium/inmemory/mutations/AddPropertyValueMutation.java
- sql/src/main/java/org/vertexium/sql/SqlTableEdge.java
- sql/src/main/java/org/vertexium/sql/SqlTableElement.java
- sql/src/main/java/org/vertexium/sql/SqlTableVertex.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
> InMemory/SQL: Fix historical metadata values getting lost for property metadata-only changes

- CHANGELOG.md
- core/src/main/java/org/vertexium/event/AddEdgeEvent.java
- core/src/main/java/org/vertexium/event/AddPropertyEvent.java
- core/src/main/java/org/vertexium/event/AddVertexEvent.java
- core/src/main/java/org/vertexium/event/DeleteEdgeEvent.java
- core/src/main/java/org/vertexium/event/DeletePropertyEvent.java
- core/src/main/java/org/vertexium/event/DeleteVertexEvent.java
- core/src/main/java/org/vertexium/event/GraphEvent.java
- core/src/main/java/org/vertexium/event/MarkHiddenEdgeEvent.java
- core/src/main/java/org/vertexium/event/MarkHiddenPropertyEvent.java
- core/src/main/java/org/vertexium/event/MarkHiddenVertexEvent.java
- core/src/main/java/org/vertexium/event/MarkVisibleEdgeEvent.java
- core/src/main/java/org/vertexium/event/MarkVisiblePropertyEvent.java
- core/src/main/java/org/vertexium/event/MarkVisibleVertexEvent.java
- core/src/main/java/org/vertexium/event/SoftDeleteEdgeEvent.java
- core/src/main/java/org/vertexium/event/SoftDeletePropertyEvent.java
- core/src/main/java/org/vertexium/event/SoftDeleteVertexEvent.java
> Graph: Remove the comparison of graph in the GraphEvent base class

- CHANGELOG.md
- core/src/main/java/org/vertexium/GraphBaseWithSearchIndex.java
- core/src/main/java/org/vertexium/GraphWithSearchIndex.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
- elasticsearch-singledocument/src/test/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndexTestBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
> Added interface GraphWithSearchIndex, which GraphBaseWithSearchIndex now implements

- core/src/main/java/org/vertexium/Metadata.java
If a Metadata object gets serialized and then deserialized, the entriesLock ends up null and was causing NullPointException's when any method tried to obtain the lock. This adds a getter method that will first check to see if the lock is null and create a new one needed.
> Repopulate the Metadata entriesLock if deserialized

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- core/src/main/java/org/vertexium/HistoricalPropertyValue.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableElement.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Logic changes to HistoryPropertyValue code to support.
#1013 Delete property event
#1035 Avoid modified events with no modifications (mostly InMemory implementation)
> History enhancements

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloFindPathStrategy.java
- accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
- core/src/main/java/org/vertexium/GraphBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Don't merge this PR. Want to see if test passes in Travis.
> When find paths max 2 hops away, return paths one hop away as well

- CHANGELOG.md
Merge https://github.com/visallo/vertexium/pull/138 first
> fix changelog to reflect find path bug fix is in 2.5.4

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- accumulo/src/main/java/org/vertexium/accumulo/ElementMutationBuilder.java
- accumulo/src/main/java/org/vertexium/accumulo/LazyMutableProperty.java
- accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueHdfsRef.java
- accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTable.java
- accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTableRef.java
- accumulo/src/main/java/org/vertexium/accumulo/keys/DataTableRowKey.java
- accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
- core/src/main/java/org/vertexium/property/StreamingPropertyValueRef.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryStreamingPropertyValueRef.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableElement.java
- sql/src/main/java/org/vertexium/sql/SqlStreamingPropertyValueRef.java
- sql/src/main/java/org/vertexium/sql/SqlTableElement.java
With the timestamp in the SPV row key it prevents the cleanup of history.
> Changed: Removed timestamp from streaming property value row key.

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/tools/DeleteHistoricalLegacyStreamingPropertyValueData.java
- accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
Cherry picked from... https://github.com/visallo/vertexium/pull/150
> Fixed: DeleteHistoricalLegacyStreamingPropertyValueData with property keys having common prefix

- CHANGELOG.md
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSearchIndexConfiguration.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchGraphQuery.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchVertexQuery.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchGraphQueryIdIterable.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/utils/InfiniteScrollIterable.java
- elasticsearch2/src/main/java/org/vertexium/elasticsearch2/Elasticsearch2SearchIndex.java
- elasticsearch2/src/main/java/org/vertexium/elasticsearch2/ElasticsearchGraphQueryIdIterable.java
- elasticsearch2/src/main/java/org/vertexium/elasticsearch2/ElasticsearchSearchGraphQuery.java
- elasticsearch2/src/main/java/org/vertexium/elasticsearch2/ElasticsearchSearchIndexConfiguration.java
- elasticsearch2/src/main/java/org/vertexium/elasticsearch2/ElasticsearchSearchQueryBase.java
- elasticsearch2/src/main/java/org/vertexium/elasticsearch2/ElasticsearchSearchVertexQuery.java
- elasticsearch2/src/main/java/org/vertexium/elasticsearch2/utils/InfiniteScrollIterable.java
This is my attempt to introduce the ES scroll API. If current users of the query API do not specify a limit they will get the scroll API by default.
> Added: Elasticsearch scroll API support

- CHANGELOG.md
- core/src/main/java/org/vertexium/mutation/ExistingElementMutation.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
I'll cherry pick this to `2.5.x` and `master` after it has been merged
> Alter property visibility

- CHANGELOG.md
- core/src/main/java/org/vertexium/DefaultGraphVisitor.java
- core/src/main/java/org/vertexium/Graph.java
- core/src/main/java/org/vertexium/GraphBase.java
- core/src/main/java/org/vertexium/GraphVisitor.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
I'm writing a data validation routine that needs to look at all aspects of a graph
> Added: GraphVisitor to visit elements, properties, extended data rows using a visitor pattern

- CHANGELOG.md
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/DefaultIndexSelectionStrategy.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/DefaultIndexSelectionStrategy.java
Also fixed a bug where indicesToQueryArray was not being updated
> Reduced DefaultIndexSelectionStrategy cache load time from 1hr to 5min

- CHANGELOG.md
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
The element type was improperly being set to vertex.
> Fix: Extended data element type value for edges

- CHANGELOG.md
- core/src/main/java/org/vertexium/query/CompositeGraphQuery.java
- core/src/main/java/org/vertexium/query/GeoCompare.java
- core/src/main/java/org/vertexium/query/Query.java
- core/src/main/java/org/vertexium/query/QueryBase.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Also implemented support for all compare operators with DateOnly properties in Elasticsearch 5
> Added two new has methods to allow searching across multiple properties

- CHANGELOG.md
- core/src/main/java/org/vertexium/query/CompositeGraphQuery.java
- core/src/main/java/org/vertexium/query/Query.java
- core/src/main/java/org/vertexium/query/QueryBase.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticSearchSingleDocumentSearchQueryBase.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/ElasticsearchSingleDocumentSearchIndex.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/MetadataTablePropertyNameVisibilitiesStore.java
- elasticsearch-singledocument/src/main/java/org/vertexium/elasticsearch/PropertyNameVisibilitiesStore.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/MetadataTablePropertyNameVisibilitiesStore.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/PropertyNameVisibilitiesStore.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
This will allow a search to find all elements that use a particular authorization
> Add hasAuthorization to Query

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraphConfiguration.java
- accumulo/src/main/java/org/vertexium/accumulo/ElementMutationBuilder.java
- accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueHdfs.java
- accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueHdfsRef.java
- accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTable.java
- accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTableData.java
- accumulo/src/main/java/org/vertexium/accumulo/StreamingPropertyValueTableDataRef.java
- accumulo/src/main/java/org/vertexium/accumulo/mapreduce/ElementMapper.java
- accumulo/src/main/java/org/vertexium/accumulo/util/DataInDataTableStreamingPropertyValueStorageStrategy.java
- accumulo/src/main/java/org/vertexium/accumulo/util/HdfsLargeDataStore.java
- accumulo/src/main/java/org/vertexium/accumulo/util/LimitOutputStream.java
- accumulo/src/main/java/org/vertexium/accumulo/util/OverflowIntoHdfsStreamingPropertyValueStorageStrategy.java
- accumulo/src/main/java/org/vertexium/accumulo/util/StreamingPropertyValueStorageStrategy.java
- accumulo/src/test/java/org/vertexium/accumulo/AccumuloResource.java
- core/src/main/java/org/vertexium/property/DefaultStreamingPropertyValue.java
- core/src/main/java/org/vertexium/property/StreamingPropertyValue.java
- core/src/main/java/org/vertexium/util/ByteRingBuffer.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryStreamingPropertyValue.java
- sql/src/main/java/org/vertexium/sql/SqlStreamingPropertyTable.java
- sql/src/main/java/org/vertexium/sql/SqlStreamingPropertyValue.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
- tools/src/main/java/org/vertexium/tools/GraphRestore.java
- tools/src/test/java/org/vertexium/tools/BackupRestoreTest.java
Kind of a scary change, not sure if this should hold off until the next major release.
> Added: Accumulo in table storage of streaming property value data

- CHANGELOG.md
- core/src/main/java/org/vertexium/ElementBase.java
- core/src/main/java/org/vertexium/ExtendedDataRow.java
- core/src/main/java/org/vertexium/ExtendedDataRowBase.java
- core/src/main/java/org/vertexium/query/SortContainersComparator.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
- test/src/main/java/org/vertexium/test/util/VertexiumAssert.java
Review and merge https://github.com/visallo/vertexium/pull/211 first
> Added: Sorting and aggregating of row ids and table names

- accumulo/src/main/java/org/vertexium/accumulo/AccumuloEdge.java
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloVertex.java
- cli/pom.xml
- cli/src/main/java/org/vertexium/cli/CliVertexiumCypherQueryContext.java
- cli/src/main/java/org/vertexium/cli/ExecuteCypherQuery.java
- cli/src/main/java/org/vertexium/cli/ParametersBase.java
- cli/src/main/java/org/vertexium/cli/VertexiumScript.java
- cli/src/main/java/org/vertexium/cli/VertexiumShell.java
- core/src/main/java/org/vertexium/Edge.java
- core/src/main/java/org/vertexium/EdgeInfo.java
- core/src/main/java/org/vertexium/EdgeInfoEdge.java
- core/src/main/java/org/vertexium/Element.java
- core/src/main/java/org/vertexium/ElementBase.java
- core/src/main/java/org/vertexium/ExtendedDataRowBase.java
- core/src/main/java/org/vertexium/VertexiumObject.java
- cypher/src/main/java/org/vertexium/cypher/VertexiumCypherQueryContext.java
- cypher/src/main/java/org/vertexium/cypher/executor/MatchClauseExecutor.java
- cypher/src/main/java/org/vertexium/cypher/functions/date/CypherUnaryDateFunction.java
- cypher/src/main/java/org/vertexium/cypher/functions/date/DayFunction.java
- cypher/src/main/java/org/vertexium/cypher/functions/date/MonthFunction.java
- cypher/src/main/java/org/vertexium/cypher/functions/date/YearFunction.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryElement.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryVertex.java
- sql/src/main/java/org/vertexium/sql/SqlExtendedDataTable.java
See https://github.com/visallo/vertexium/pull/217 first
The big thing added here is the use of `EdgeInfoEdge`. This is like an edge but only populated from what is returned by the vertices' edge info results which in Cypher is all you need many of the times.
> Edge info edge

- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/utils/FlushObjectQueue.java
This is another attempt to fix the retry logic of ES. This is working pretty well on my project and it moves the logic out of `Elasticsearch5SearchIndex`.
> Another attempt to fix the Elasticsearch retry logic

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- accumulo/src/main/java/org/vertexium/accumulo/keys/KeyHelper.java
- core/src/main/java/org/vertexium/Graph.java
- core/src/main/java/org/vertexium/GraphBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Adds methods that will allow bulk loading of extended data rows
> Load Extended Data Rows for Ranges of Elements

- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Fix a bug in the indexing of ExistingElementMutation that was causing old values to be lost when adding a new property value by a different key
> Fix a bug in the indexing of ExistingElementMutation

- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/utils/FlushObjectQueue.java
Remove the thread local ES flush queue and have all threads share a single queue. This will allow client applications to more effectively use multithreading.
> Shared ElasticsearchIndex Flush Queue

- accumulo-blueprints/pom.xml
- accumulo-iterators/pom.xml
- accumulo-migrations/pom.xml
- accumulo-titan-hadoop/pom.xml
- accumulo/pom.xml
- blueprints-test/pom.xml
- blueprints/pom.xml
- cli/pom.xml
- core/pom.xml
- cypher/pom.xml
- elasticsearch5-plugin/pom.xml
- elasticsearch5/pom.xml
- inmemory/pom.xml
- kryo-serializer/pom.xml
- multimodule-test/accumulo-elasticsearch5/pom.xml
- multimodule-test/pom.xml
- pom.xml
- security/pom.xml
- sql/pom.xml
- test/pom.xml
- tools/pom.xml
- xstream-serializer/pom.xml
Submitting this as a PR to ensure that the build passes
> bump pom versions to 4.0-SNAPSHOT

- CHANGELOG.md
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
3.2.x PR: https://github.com/visallo/vertexium/pull/257
> fix not adding all geoshape/geopoint fields to index for existing elements

- CHANGELOG.md
- accumulo-iterators/src/main/java/org/vertexium/accumulo/iterator/model/EdgesWithCount.java
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloVertex.java
- accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
- core/src/main/java/org/vertexium/EdgesSummary.java
- core/src/main/java/org/vertexium/Vertex.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryVertex.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Can you think of anything else we need to get inverse of relationship details pane working?
> Added: Method to Vertex to get more detailed edge summary

- CHANGELOG.md
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
https://github.com/visallo/vertexium/pull/259
> Move property conversion so it's called on updates (master)

- accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloVertex.java
- core/src/main/java/org/vertexium/search/DefaultSearchIndex.java
- core/src/main/java/org/vertexium/search/SearchIndex.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- elasticsearch5/src/test/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndexTest.java
3.2 PR: https://github.com/visallo/vertexium/pull/265
> Reload Elasticsearch IndexInfo Cache when Property Definitions Change (master)

- core/src/main/java/org/vertexium/query/DefaultGraphQueryIterable.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
https://github.com/visallo/vertexium/pull/267
> Fix query search using sandboxed querystring, and add test (master)

- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
Making these methods public help when creating a custom IndexSelectionStrategy
> Make methods public

- pom.xml
No particular feature we're looking for in the upgrade. Just a bit of housekeeping. Curator release notes are here: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12314425&version=12338714
> Update to the Latest 2.x Curator

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java
- core/src/main/java/org/vertexium/Edge.java
- core/src/main/java/org/vertexium/EdgeVertexIds.java
- core/src/main/java/org/vertexium/ElementBase.java
- core/src/main/java/org/vertexium/PropertyDefinition.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
completes... https://github.com/visallo/vertexium/issues/295
@jharwig can you look at the unit test in `GraphTestBase` and make sure this will do what you need.
> Query edges with a given in or out vertex

- accumulo/src/main/java/org/vertexium/accumulo/AccumuloElement.java
- core/src/main/java/org/vertexium/ElementBase.java
- core/src/main/java/org/vertexium/util/PropertyCollection.java
Update property loading to optimize the case where both key and name are known.
> Optimize property loading

- core/src/main/java/org/vertexium/query/DefaultExtendedDataQuery.java
- core/src/main/java/org/vertexium/query/DefaultMultiVertexQuery.java
- core/src/main/java/org/vertexium/query/QueryStringQueryParameters.java
- core/src/main/java/org/vertexium/query/VertexQueryBase.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchExtendedDataQuery.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchVertexQuery.java
Added `toString` methods to more of the QueryBase subclasses to ensure that they display all relevant information.
> toString for all Query Classes (4.1.1.x)

- core/src/main/java/org/vertexium/query/DefaultExtendedDataQuery.java
- core/src/main/java/org/vertexium/query/DefaultMultiVertexQuery.java
- core/src/main/java/org/vertexium/query/QueryStringQueryParameters.java
- core/src/main/java/org/vertexium/query/VertexQueryBase.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchExtendedDataQuery.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchVertexQuery.java
4.1.1.x PR: https://github.com/visallo/vertexium/pull/307
> toString for all Query Classes

- CHANGELOG.md
- core/src/main/java/org/vertexium/query/Compare.java
- core/src/main/java/org/vertexium/query/QueryBase.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Added the ability to perform a term query by prefix using a new Compare.STARTS_WITH predicate.
> Add Compare.STARTS_WITH Predicate

- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchVertex.java
I can't remember what I needed this for, I can look Tuesday but I know this fixed my issue
> Elasticsearch: support query from ElasticsearchVertex

- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
Convert synchronized code to use StampedLock in an attempt to prevent deadlocks and improve performance. Since most of the case are reads, using a synchronize block was causing more than necessary contention.
> Improve Accumulo Metadata Locking

- CHANGELOG.md
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/utils/InfiniteScrollIterable.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
4.1.1.x PR: https://github.com/visallo/vertexium/pull/326
Submitted PR to confirm travis build success.
> NPE in InfiniteScrollIterable if no matching property name has been found when applying filters

- CHANGELOG.md
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
https://github.com/visallo/vertexium/pull/333
> Allow decimal intervals for histogram aggregation

- CHANGELOG.md
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5SearchIndex.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchIndexConfiguration.java
The current code to run embedded ES is broken and since it is not recommended to run ES that way, I've removed that option when not in `test` mode.
> removed ability to run embedded elasticsearch not in test since it is not recommended

- pom.xml
hopefully fixes the Github warning
> upgrade checkstyle

- accumulo/src/main/java/org/vertexium/accumulo/AccumuloVertex.java
- core/src/main/java/org/vertexium/Graph.java
- core/src/main/java/org/vertexium/GraphBase.java
- core/src/main/java/org/vertexium/Vertex.java
- core/src/main/java/org/vertexium/query/EmptyResultsGraphQuery.java
- core/src/main/java/org/vertexium/query/Query.java
- core/src/main/java/org/vertexium/query/QueryBase.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchVertex.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryVertex.java
Removed from really old deprecated methods. Trying to clean up some old code to make it easier to transition to Streams
> remove old deprecated methods

- CHANGELOG.md
- accumulo/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- accumulo/src/main/java/org/vertexium/accumulo/keys/KeyHelper.java
- accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
- core/src/main/java/org/vertexium/Graph.java
- core/src/main/java/org/vertexium/IdRange.java
- core/src/main/java/org/vertexium/Range.java
- core/src/main/java/org/vertexium/query/Compare.java
- core/src/main/java/org/vertexium/util/ObjectUtils.java
- core/src/test/java/org/vertexium/RangeTest.java
- core/src/test/java/org/vertexium/util/ObjectUtilsTest.java
- cypher/src/main/java/org/vertexium/cypher/executionPlan/AggregationFunctionInvocationExecutionStep.java
- cypher/src/main/java/org/vertexium/cypher/executionPlan/BinaryExpressionExecutionStep.java
- cypher/src/main/java/org/vertexium/cypher/executionPlan/ComparisonExpressionExecutionStep.java
- cypher/src/main/java/org/vertexium/cypher/executionPlan/InExecutionStep.java
- cypher/src/main/java/org/vertexium/cypher/executionPlan/ReturnExecutionStep.java
- cypher/src/main/java/org/vertexium/cypher/executionPlan/SetItemExecutionStep.java
- cypher/src/main/java/org/vertexium/cypher/functions/aggregate/AverageFunction.java
- cypher/src/main/java/org/vertexium/cypher/functions/aggregate/MaxFunction.java
- cypher/src/main/java/org/vertexium/cypher/functions/aggregate/MinFunction.java
- cypher/src/main/java/org/vertexium/cypher/functions/aggregate/SumFunction.java
- cypher/src/main/java/org/vertexium/cypher/utils/CypherObjectUtils.java
- elasticsearch5-graph/src/main/java/org/vertexium/elasticsearch5/Elasticsearch5Graph.java
- elasticsearch5-graph/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
This PR is against `streams-es-graph` branch. Unit tests will still fail but I wanted to have you look at these changes.
> add query range support

- accumulo/src/test/java/org/vertexium/accumulo/AccumuloGraphTestBase.java
- core/src/main/java/org/vertexium/util/IncreasingTime.java
Just some debugging code I use on my project
> add debugging tools

- CHANGELOG.md
- elasticsearch5-plugin/src/main/java/org/vertexium/elasticsearch5/plugin/VertexiumMapperQueryParser.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
Cherry-pick from Master: https://github.com/visallo/vertexium/commit/18ed5a32e2e74173f6f48227c8f97950e23c71bd
> ES Field wildcard queries

- CHANGELOG.md
Related to https://github.com/visallo/vertexium/pull/384
> move es change entry from 4.7.0 to 4.6.2

- CHANGELOG.md
- elasticsearch5/src/main/java/org/vertexium/elasticsearch5/ElasticsearchSearchQueryBase.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
4.6.x PR: https://github.com/visallo/vertexium/pull/386
> Similar to search hits master

- CHANGELOG.md
- accumulo/graph/src/main/java/org/vertexium/accumulo/AccumuloGraph.java
- accumulo/graph/src/main/java/org/vertexium/accumulo/ElementMutationBuilder.java
- accumulo/graph/src/main/java/org/vertexium/accumulo/LazyMutableProperty.java
- accumulo/graph/src/main/java/org/vertexium/accumulo/LazyPropertyMetadata.java
- accumulo/graph/src/test/java/org/vertexium/accumulo/AccumuloResource.java
- core/src/main/java/org/vertexium/DefaultMetadataPlugin.java
- core/src/main/java/org/vertexium/GraphBase.java
- core/src/main/java/org/vertexium/GraphBaseWithSearchIndex.java
- core/src/main/java/org/vertexium/GraphConfiguration.java
- core/src/main/java/org/vertexium/MapMetadata.java
- core/src/main/java/org/vertexium/Metadata.java
- core/src/main/java/org/vertexium/MetadataPlugin.java
- elasticsearch5/search-index/src/test/java/org/vertexium/elasticsearch5/ElasticsearchResource.java
- elasticsearch7/search-index/src/test/java/org/vertexium/elasticsearch7/ElasticsearchResource.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryEdgeTable.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryGraph.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTable.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableEdge.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableElement.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryTableVertex.java
- inmemory/src/main/java/org/vertexium/inmemory/InMemoryVertexTable.java
- inmemory/src/main/java/org/vertexium/inmemory/mutations/AddPropertyValueMutation.java
- inmemory/src/test/java/org/vertexium/inmemory/InMemoryGraphTest.java
- test/src/main/java/org/vertexium/test/GraphTestBase.java
- test/src/main/java/org/vertexium/test/TestMetadataPlugin.java
This PR build off of so review and merge this first https://github.com/visallo/vertexium/pull/424
We should talk before merging this
> Less metadata

- core/src/main/java/org/vertexium/metric/DropWizardMetricRegistry.java
Easy to enable in debugger using...
`getGraph().getMetricsRegistry().startConsoleReporter(5000)`
> add helper methods to easily enable Drop Wizard Metrics ConsoleReporter

- core/src/main/java/org/vertexium/ProgressCallback.java
Exposing step message format for internationalisation downstream
> expose step message for internationalisation
